"""added server pic url and server cover pic url

Revision ID: aec16a568acf
Revises: 370b9b479856
Create Date: 2022-07-25 21:48:08.655853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec16a568acf'
down_revision = '370b9b479856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('server_pic_url', sa.String(length=255), nullable=True))
    op.add_column('servers', sa.Column('server_cover_pic_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'server_cover_pic_url')
    op.drop_column('servers', 'server_pic_url')
    # ### end Alembic commands ###
