"""added server_pic_url to servers model and components and store

Revision ID: 70079d5191a9
Revises: 06806c451452
Create Date: 2022-07-29 09:28:13.408922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70079d5191a9'
down_revision = '06806c451452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'channels', ['name'])
    op.add_column('servers', sa.Column('server_pic_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'server_pic_url')
    op.drop_constraint(None, 'channels', type_='unique')
    # ### end Alembic commands ###
