"""removed unique key constraint on "names" of channels

Revision ID: 704a2f0d72fe
Revises: 06806c451452
Create Date: 2022-07-28 16:17:30.698045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704a2f0d72fe'
down_revision = '06806c451452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('channels_name_key', 'channels', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('channels_name_key', 'channels', ['name'])
    # ### end Alembic commands ###
