"""made changes to servers-users members table column names

Revision ID: b5b1e296e232
Revises: bea5afac0236
Create Date: 2022-07-24 20:58:19.755744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b1e296e232'
down_revision = 'bea5afac0236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('members', sa.Column('server_id', sa.Integer(), nullable=False))
    op.drop_constraint('members_users_fkey', 'members', type_='foreignkey')
    op.drop_constraint('members_servers_fkey', 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'members', 'servers', ['server_id'], ['id'])
    op.drop_column('members', 'servers')
    op.drop_column('members', 'users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('users', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('members', sa.Column('servers', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key('members_servers_fkey', 'members', 'servers', ['servers'], ['id'])
    op.create_foreign_key('members_users_fkey', 'members', 'users', ['users'], ['id'])
    op.drop_column('members', 'server_id')
    op.drop_column('members', 'user_id')
    # ### end Alembic commands ###
