"""changed back to members table

Revision ID: 370b9b479856
Revises: b5b1e296e232
Create Date: 2022-07-25 09:10:44.927648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370b9b479856'
down_revision = 'b5b1e296e232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('users', sa.Integer(), nullable=False))
    op.add_column('members', sa.Column('servers', sa.Integer(), nullable=False))
    op.drop_constraint('members_server_id_fkey', 'members', type_='foreignkey')
    op.drop_constraint('members_user_id_fkey', 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'servers', ['servers'], ['id'])
    op.create_foreign_key(None, 'members', 'users', ['users'], ['id'])
    op.drop_column('members', 'user_id')
    op.drop_column('members', 'server_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('server_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('members', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key('members_user_id_fkey', 'members', 'users', ['user_id'], ['id'])
    op.create_foreign_key('members_server_id_fkey', 'members', 'servers', ['server_id'], ['id'])
    op.drop_column('members', 'servers')
    op.drop_column('members', 'users')
    # ### end Alembic commands ###
